ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT

      COMMON/MASSES/ MDL_MT


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_22, GC_25, GC_34, GC_28, GC_31

      COMMON/COUPLINGS/ GC_22, GC_25, GC_34, GC_28, GC_31

